services:
- name: right-leg
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
- name: right-arm
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
- name: left-leg
  triggerevent: sh.keptn.event.dev.artifact-delivery.triggered
