stage: dev

# applies to all deployments in this chart
replicaCount: 2
images:
  repositoryDirname: ghcr.io/podtato-head
  pullPolicy: IfNotPresent
  pullSecrets: []

rightLeg:
  repositoryBasename: podtato-right-leg
  tag: "{{ keptn/imageVersion }}"
  serviceType: ClusterIP
  servicePort: 9004

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

