stage: dev
# applies to all deployments in this chart
replicaCount: 2

rightArm:
  repositoryBasename: podtato-right-arm
  tag: "{{ keptn/imageVersion }}"
  serviceType: ClusterIP
  servicePort: 9005

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

